# Generated by Django 5.2.5 on 2025-08-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='route',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
