# Generated by Django 5.2.5 on 2025-08-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_spot_options_alter_spot_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='total_minutes',
        ),
        migrations.AddField(
            model_name='plan',
            name='route',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
