# Generated by Django 5.2.5 on 2025-08-23 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_remove_plan_is_published_remove_plan_total_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='shot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='plans.spot'),
        ),
        migrations.AddField(
            model_name='plan',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='path_geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['plan', 'order'], name='plans_photo_plan_id_3c448c_idx'),
        ),
    ]
