# Generated by Django 5.2.5 on 2025-08-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_photo_lat_photo_lng_photo_shot_at_photo_spot_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='photo',
            name='plans_photo_plan_id_3c448c_idx',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='path_geojson',
            new_name='route_geojson',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='shot_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='body',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='route',
        ),
        migrations.AddField(
            model_name='spot',
            name='transport_to_next',
            field=models.CharField(choices=[('walk', '徒歩'), ('train', '電車'), ('bus', 'バス'), ('car', '車'), ('bike', '自転車'), ('boat', '船'), ('other', 'その他')], default='walk', max_length=10),
        ),
    ]
