# Generated by Django 5.2.5 on 2025-08-23 13:21
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('plans', '0006_remove_photo_plans_photo_plan_id_3c448c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='route_geojson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
